<div data-bind="scope:'section'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app":{
                "components":{
                    "section":{
                        "component": "TestJean_ModuleJean/js/section",
                        "template": "TestJean_ModuleJean/section"
                    }
                }
            }
        }
    }
</script>